---
title: "Lecture-code"
format:
  pdf:
    fontsize: 8pt
---

# Basic Operations

```{r, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3, fig.align = "center"}
floor(6.3)  # same as 6.3 %/% 1

# Temperature vector
temp <- c(273, 283, 293, 303, 313, 323, 333, 343, 353, 363, 373)
length(temp)
r_temp <- rev(temp)
summary(r_temp)

# Vapor pressure
vp <- c(4.6, 9.2, 17.5, 31.8, 55.3, 92.5, 149.4, 233.7, 355.1, 525.8, 760.0)
vapor <- data.frame(temp, vp)
vapor$temp
vapor$vp
inv_temp <- 1/vapor$temp
plot(vapor$temp, vapor$vp)
```

# Generating numbers & plotting

```{r, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3, fig.align = "center"}
seq(0,1,length = 15)
rep("A", 10)
runif(50, 0, 1)

x <- -50:50
y <- x^3
plot(x,y, type = "p")
plot(x,y, type = "l")
plot(x,y, type = "b")
plot(x,y, type = "n")
plot(x,y, type = "h")
plot(x, y, type = "l", lty = 1:4)

x <- 0:50
y <- x^3
plot(x, y, type = "p", pch = "💀")

hist(trunc(100*runif(1000)))
hist(rnorm(1e6,5,5))
hist(rexp(1e6), nclass = 35)
barplot(trunc(10*runif(10)))
boxplot(rexp(1000))
```

# Scatter & line plots

```{r, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3, fig.align = "center"}
plot(2:10, 32:40, pch = 10)
x <- seq(2, 10, length = 20)
y <- seq(32, 40, length = 20)
points(x^2, y)
plot(2:10, 32:40, pch = 15, ylim = c(0,100))
lines(x, y)
```

# Residual plots example

```{r, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3, fig.align = "center"}
x <- runif(100)
plot(floor(10*x), 10*x, pch = 10)
points(ceiling(10*x), 10*x, pch = 15, col = "blue")
points(round(10*x), 10*x, pch = 5, col = "red")
abline(0,1)
```

# Trigonometric functions

```{r, warning = FALSE, message = FALSE}
x <- seq(0, 2*pi, length = 100)
plot(x, sin(x), type = "l", col = "blue")
points(x, cos(x), type = "l", col = "red")
abline(h=0)
```

# Simple Regression Example

```{r, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3, fig.align = "center",}
Age <- c(15.50, 23.75, 8.00, 17.00, 5.50, 19.00, 
24.00, 2.50, 7.50, 11.00, 13.00, 3.75, 25.00, 9.75, 
22.00, 18.00, 6.00, 12.50, 2.00, 21.50)
Shear <- c(2158.70, 1678.15, 2316.00, 2061.30, 2207.50, 
1708.30, 1784.70, 2575.00, 2357.90, 2256.70, 2165.20, 
2399.55, 1779.80, 2336.75, 1765.30, 2053.50, 2414.40, 
2200.50, 2654.20, 1753.70)

plot(Age, Shear)
Rocket.Data <- data.frame(Shear, Age)

n <- length(Age)
x <- Age; y <- Shear
Sxx <- sum(x^2) - (sum(x))^2/n
Sxy <- sum(x*y) - sum(x)*sum(y)/n
SST <- sum(y^2) - (sum(y))^2/n
SSRes <- SST - Sxy^2/Sxx
hatbeta1 <- Sxy/Sxx
hatbeta0 <- mean(y) - hatbeta1*mean(x)
hatsigma2 <- SSRes/(n-2)
errorbeta1 <- sqrt(hatsigma2/Sxx)
errorbeta0 <- sqrt(hatsigma2*(1/n + mean(x)^2/Sxx))

abline(hatbeta0, hatbeta1, col = "red")

# Hypothesis testing
(tvalue <- hatbeta1/errorbeta1)
2*(1 - pt(abs(tvalue), df = n-2))
```

# Linear Regression using lm

```{r, warning = FALSE, message = FALSE, fig.width = 4, fig.height = 3, fig.align = "center"}
Out1 <- lm(y ~ x)
summary(Out1)
plot(Out1)
anova(Out1)
abline(2627.82, -37.15)
Out1$fitted.values
resid(Out1)
```


```{r leverage_influence}
library(MPV)
data(table.b9)
attach(table.b9)
colnames(table.b9)
plot(table.b9$x1, table.b9$y)
# scatter plot comb for x1, x2, x3, x4  each vs y
plot(table.b9$x2, table.b9$y)
plot(table.b9$x3, table.b9$y)
plot(table.b9$x4, table.b9$y)

lm1 <- lm(y ~ x1 + x2 + x3 + x4, data = table.b9)
summary(lm1)
library(patchwork)

# parmfrow
par(mfrow = c(2, 2))
plot(lm1, which = 1)
plot(lm1, which = 2)
plot(lm1, which = 3)
plot(lm1, which = 4)

# identify points with high leverage
plot(lm1, which = 5)
# hat values

plot(hatvalues(lm1), type = "h")
p <- length(coef(lm1))
abline(h = 2*5/length(y))
identify(hatvalues(lm1), labels = 1:nrow(table.b9))


# cook's distance



library(MPV)
data(p8.3)
head(p8.3)
fit <- lm(y ~ x1 + x2 , data = p8.3)
dffits <- dffits(fit)
plot(dffits, type = "h")
abline(0,0, col = "black")
p <- length(coef(fit))
n <- length(p8.3$y)
cutoff <- 2*sqrt(p/n)
abline(h = cutoff, col = "red", lty = 2)
abline(h = -cutoff, col = "red", lty = 2)
labels <- 1:nrow(p8.3)
identify(dffits, labels = labels)

dbetafits <- dfbetas(fit)
plot(dbetafits[,1], type = "h", main = "dfbeta for x1")
abline(0,0, col = "black")
cutoff_dbeta <- 2/sqrt(n)
abline(h = cutoff_dbeta, col = "red", lty = 2)
abline(h = -cutoff_dbeta, col = "red", lty = 2)


dbetafits <- dfbetas(fit)
plot(dbetafits[,2], type = "h", main = "dfbeta for x2")
abline(0,0, col = "black")
cutoff_dbeta <- 2/sqrt(n)
abline(h = cutoff_dbeta, col = "red", lty = 2)
abline(h = -cutoff_dbeta, col = "red", lty = 2)



x <- c(0.25, 0.50, 0.75, 1, 1.25, 1.50, 1.75, 2.00, 2.25, 2.50)
y <- c(1.42, 1.39, 1.55, 1.89, 2.43, 3.15, 4.05, 5.15, 6.43, 7.89)

plot(x, y)

# simple
fit1 <- lm(y ~ x)
abline(fit1, col = "red")
# quadratic
fit2 <- lm(y ~ x + I(x^2))
curve(predict(fit2, newdata = data.frame(x = x)), add = TRUE, col = "blue")
# cubic 
fit3 <- lm(y ~ x + I(x^2) + I(x^3))
curve(predict(fit3, newdata = data.frame(x = x)), add = TRUE, col = "green")
anova(fit1, fit2, fit3)


```
